export const SELECTED_LAND = "SELECTED_LAND";
export const SELECTED_LAND_SIDEBAR_STATUS = "SELECTED_LAND_SIDEBAR_STATUS";
export const SELECTED_LAND_OVERLAY_STATUS = "SELECTED_LAND_OVERLAY_STATUS";

export const GOTO_LOCATION = "GOTO_LOCATION";
export const SET_LOCATION = "SET_LOCATION";

export const CREATE_LAND = "CREATE_LAND";
export const RETRIEVE_LANDS = "RETRIEVE_LANDS";
export const RETRIEVE_OWNED_LANDS = "RETRIEVE_OWNED_LANDS";
export const GET_LAND = "GET_LAND";
export const UPDATE_LAND = "UPDATE_LAND";
export const DELETE_LAND = "DELETE_LAND";
export const GET_LANDS_STATISTICS = "GET_LANDS_STATISTICS";
export const DELETE_ALL_LANDS = "DELETE_ALL_LANDS";
export const MANAGE_LAND_EVENT = "MANAGE_LAND_EVENT";

export const SET_FILTERS = "FILTERS_SET_ALL";
export const SET_BID_TYPE_FILTER = "FILTERS_SET_BID_TYPE";
export const SET_AREA_SIZE_FILTER = "FILTERS_SET_AREA_SIZE";
export const SET_ZONE_FILTER = "FILTERS_SET_ZONE";
export const SET_LEFT_SIDEBAR_STATUS = "SET_LEFT_SIDEBAR_STATUS";
export const SET_MINIMAP_STATUS = "SET_MINIMAP_STATUS";
export const SET_3D_VIEW_STATUS = "SET_3D_VIEW_STATUS";
export const RESET_FILTERS = "FILTERS_RESET";

export const WALLET_CONNECT = "WALLET_CONNECT"
export const WALLET_CHANGE = "WALLET_CHANGE"
export const WALLET_RESET = "WALLET_RESET"
export const WALLET_BALANCE = "WALLET BALANCE"

export const BLOCKCHAIN_CONNECT = "BLOCKCHAIN_CONNECT"
export const BLOCKCHAIN_RESET = "BLOCKCHAIN_RESET"
